### ISSUE TITLE
Tracking Issue for DocInsight 2024 Beta

### ISSUE THREAD

**Issue by zuobaoquan** [devjetsoftware/docinsight-support#13]
This tracking issue lists known issues that should be resolved before releasing DocInsight 2024.

## General

- [ ] Check for Updates
- [ ] Licensing

## Documentation

- [ ] Resolve `cref`
- [ ] Auto-inherited documentation
- [ ] Implements section
- [ ] Check more XML documentation errors
- [ ] Fix definition syntax
- [ ] Generate type hyperlinks
- [ ] Fix formatter tests
- [ ] Failed to update documentation for single-line enum members
- [ ] Collect user images when building docs

## DocInspector/DocExplorer

- [ ] Reload/Go back/Go forward navigation
- [ ] Breadcrumb navigation bar
- [ ] Editor toolbar is missing in DocExplorer
- [ ] Code navigation doesn't work in DocInspector
